package capabilityCommunity
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.

type FieldName string
const (
	PlatformID FieldName = "platform_id"
	ID FieldName = "id"
	Name FieldName = "name"
	Description FieldName = "description"
	Advocate FieldName = "advocate"
	CreatedBy FieldName = "created_by"
)

type IndexName string
const (
	PlatformIDIndex IndexName = "PlatformIDIndex"
)
