package dialogEntry
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.

type FieldName string
const (
	DialogID FieldName = "dialog_id"
	Context FieldName = "context"
	Subject FieldName = "subject"
	Updated FieldName = "updated"
	Dialog FieldName = "dialog"
	Comments FieldName = "comments"
	LearnMoreLink FieldName = "learn_more_link"
	LearnMoreContent FieldName = "learn_more_content"
	BuildBranch FieldName = "build_branch"
	CultivationBranch FieldName = "cultivation_branch"
	MasterBranch FieldName = "master_branch"
	BuildID FieldName = "build_id"
)
