package userAttribute
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.

type FieldName string
const (
	UserID FieldName = "user_id"
	AttrKey FieldName = "attr_key"
	AttrValue FieldName = "attr_value"
	Default FieldName = "default"
)
