package userAttribute
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.
import (
	"github.com/aws/aws-sdk-go/aws"
	common "github.com/adaptiveteam/adaptive/daos/common"
	core "github.com/adaptiveteam/adaptive/core-utils-go"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/pkg/errors"
	"fmt"
)


// Create saves the UserAttribute.
func Create(userAttribute UserAttribute) common.ConnectionProc {
	return func (conn common.DynamoDBConnection) (err error) {
		emptyFields, ok := userAttribute.CollectEmptyFields()
		if ok {
			
			err = conn.Dynamo.PutTableEntry(userAttribute, TableName(conn.ClientID))
		} else {
			err = fmt.Errorf("Cannot create entity with empty fields: %v", emptyFields)
		}
		return
	}
}


// CreateUnsafe saves the UserAttribute.
func CreateUnsafe(userAttribute UserAttribute) func (conn common.DynamoDBConnection) {
	return func (conn common.DynamoDBConnection) {
		err2 := Create(userAttribute)(conn)
		core.ErrorHandler(err2, "daos/UserAttribute", fmt.Sprintf("Could not create userID==%s, attrKey==%s in %s\n", userAttribute.UserID, userAttribute.AttrKey, TableName(conn.ClientID)))
	}
}


// Read reads UserAttribute
func Read(userID string, attrKey string) func (conn common.DynamoDBConnection) (out UserAttribute, err error) {
	return func (conn common.DynamoDBConnection) (out UserAttribute, err error) {
		var outs []UserAttribute
		outs, err = ReadOrEmpty(userID, attrKey)(conn)
		if err == nil && len(outs) == 0 {
			err = fmt.Errorf("Not found userID==%s, attrKey==%s in %s\n", userID, attrKey, TableName(conn.ClientID))
		}
		if len(outs) > 0 {
			out = outs[0]
		}
		return
	}
}


// ReadUnsafe reads the UserAttribute. Panics in case of any errors
func ReadUnsafe(userID string, attrKey string) func (conn common.DynamoDBConnection) UserAttribute {
	return func (conn common.DynamoDBConnection) UserAttribute {
		out, err2 := Read(userID, attrKey)(conn)
		core.ErrorHandler(err2, "daos/UserAttribute", fmt.Sprintf("Error reading userID==%s, attrKey==%s in %s\n", userID, attrKey, TableName(conn.ClientID)))
		return out
	}
}


// ReadOrEmpty reads UserAttribute
func ReadOrEmpty(userID string, attrKey string) func (conn common.DynamoDBConnection) (out []UserAttribute, err error) {
	return func (conn common.DynamoDBConnection) (out []UserAttribute, err error) {
       out, err = ReadOrEmptyIncludingInactive(userID, attrKey)(conn)
       
       
		return
	}
}


// ReadOrEmptyUnsafe reads the UserAttribute. Panics in case of any errors
func ReadOrEmptyUnsafe(userID string, attrKey string) func (conn common.DynamoDBConnection) []UserAttribute {
	return func (conn common.DynamoDBConnection) []UserAttribute {
		out, err2 := ReadOrEmpty(userID, attrKey)(conn)
		core.ErrorHandler(err2, "daos/UserAttribute", fmt.Sprintf("Error while reading userID==%s, attrKey==%s in %s\n", userID, attrKey, TableName(conn.ClientID)))
		return out
	}
}


// ReadOrEmptyIncludingInactive reads UserAttribute
func ReadOrEmptyIncludingInactive(userID string, attrKey string) func (conn common.DynamoDBConnection) (out []UserAttribute, err error) {
	return func (conn common.DynamoDBConnection) (out []UserAttribute, err error) {
		var outOrEmpty UserAttribute
		ids := idParams(userID, attrKey)
		var found bool
		found, err = conn.Dynamo.GetItemOrEmptyFromTable(TableName(conn.ClientID), ids, &outOrEmpty)
		if found {
			if outOrEmpty.UserID == userID && outOrEmpty.AttrKey == attrKey {
				out = append(out, outOrEmpty)
			} else {
				err = fmt.Errorf("Requested ids: userID==%s, attrKey==%s are different from the found ones: userID==%s, attrKey==%s", userID, attrKey, outOrEmpty.UserID, outOrEmpty.AttrKey) // unexpected error: found ids != ids
			}
		}
		err = errors.Wrapf(err, "UserAttribute DAO.ReadOrEmpty(id = %v) couldn't GetItem in table %s", ids, TableName(conn.ClientID))
		return
	}
}


// ReadOrEmptyIncludingInactiveUnsafe reads the UserAttribute. Panics in case of any errors
func ReadOrEmptyIncludingInactiveUnsafeIncludingInactive(userID string, attrKey string) func (conn common.DynamoDBConnection) []UserAttribute {
	return func (conn common.DynamoDBConnection) []UserAttribute {
		out, err2 := ReadOrEmptyIncludingInactive(userID, attrKey)(conn)
		core.ErrorHandler(err2, "daos/UserAttribute", fmt.Sprintf("Error while reading userID==%s, attrKey==%s in %s\n", userID, attrKey, TableName(conn.ClientID)))
		return out
	}
}


// CreateOrUpdate saves the UserAttribute regardless of if it exists.
func CreateOrUpdate(userAttribute UserAttribute) common.ConnectionProc {
	return func (conn common.DynamoDBConnection) (err error) {
		
		var olds []UserAttribute
		olds, err = ReadOrEmpty(userAttribute.UserID, userAttribute.AttrKey)(conn)
		err = errors.Wrapf(err, "UserAttribute DAO.CreateOrUpdate(id = userID==%s, attrKey==%s) couldn't ReadOrEmpty", userAttribute.UserID, userAttribute.AttrKey)
		if err == nil {
			if len(olds) == 0 {
				err = Create(userAttribute)(conn)
				err = errors.Wrapf(err, "UserAttribute DAO.CreateOrUpdate couldn't Create in table %s", TableName(conn.ClientID))
			} else {
				emptyFields, ok := userAttribute.CollectEmptyFields()
				if ok {
					old := olds[0]
					
					
					key := idParams(old.UserID, old.AttrKey)
					expr, exprAttributes, names := updateExpression(userAttribute, old)
					input := dynamodb.UpdateItemInput{
						ExpressionAttributeValues: exprAttributes,
						TableName:                 aws.String(TableName(conn.ClientID)),
						Key:                       key,
						ReturnValues:              aws.String("UPDATED_NEW"),
						UpdateExpression:          aws.String(expr),
					}
					if names != nil { input.ExpressionAttributeNames = *names } // workaround for a pointer to an empty slice
					if  len(exprAttributes) > 0 { // if there some changes
						err = conn.Dynamo.UpdateItemInternal(input)
					} else {
						// WARN: no changes.
					}
					err = errors.Wrapf(err, "UserAttribute DAO.CreateOrUpdate(id = %v) couldn't UpdateTableEntry in table %s, expression='%s'", key, TableName(conn.ClientID), expr)
				} else {
					err = fmt.Errorf("Cannot update entity with empty required fields: %v", emptyFields)
				}
			}
		}
		return 
	}
}


// CreateOrUpdateUnsafe saves the UserAttribute regardless of if it exists.
func CreateOrUpdateUnsafe(userAttribute UserAttribute) func (conn common.DynamoDBConnection) {
	return func (conn common.DynamoDBConnection) {
		err2 := CreateOrUpdate(userAttribute)(conn)
		core.ErrorHandler(err2, "daos/UserAttribute", fmt.Sprintf("could not create or update %v in %s\n", userAttribute, TableName(conn.ClientID)))
	}
}


// Delete removes UserAttribute from db
func Delete(userID string, attrKey string) func (conn common.DynamoDBConnection) error {
	return func (conn common.DynamoDBConnection) error {
		return conn.Dynamo.DeleteEntry(TableName(conn.ClientID), idParams(userID, attrKey))
	}
}


// DeleteUnsafe deletes UserAttribute and panics in case of errors.
func DeleteUnsafe(userID string, attrKey string) func (conn common.DynamoDBConnection) {
	return func (conn common.DynamoDBConnection) {
		err2 := Delete(userID, attrKey)(conn)
		core.ErrorHandler(err2, "daos/UserAttribute", fmt.Sprintf("Could not delete userID==%s, attrKey==%s in %s\n", userID, attrKey, TableName(conn.ClientID)))
	}
}

