package strategyCommunity
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.
import (
	awsutils "github.com/adaptiveteam/adaptive/aws-utils-go"
	"github.com/aws/aws-sdk-go/aws"
	core "github.com/adaptiveteam/adaptive/core-utils-go"
	common "github.com/adaptiveteam/adaptive/daos/common"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/pkg/errors"
	"fmt"
)


// Create saves the StrategyCommunity.
func Create(strategyCommunity StrategyCommunity) common.ConnectionProc {
	return func (conn common.DynamoDBConnection) (err error) {
		emptyFields, ok := strategyCommunity.CollectEmptyFields()
		if ok {
			strategyCommunity.ModifiedAt = core.CurrentRFCTimestamp()
	strategyCommunity.CreatedAt = strategyCommunity.ModifiedAt
	
			err = conn.Dynamo.PutTableEntry(strategyCommunity, TableName(conn.ClientID))
		} else {
			err = fmt.Errorf("Cannot create entity with empty fields: %v", emptyFields)
		}
		return
	}
}


// CreateUnsafe saves the StrategyCommunity.
func CreateUnsafe(strategyCommunity StrategyCommunity) func (conn common.DynamoDBConnection) {
	return func (conn common.DynamoDBConnection) {
		err2 := Create(strategyCommunity)(conn)
		core.ErrorHandler(err2, "daos/StrategyCommunity", fmt.Sprintf("Could not create id==%s in %s\n", strategyCommunity.ID, TableName(conn.ClientID)))
	}
}


// Read reads StrategyCommunity
func Read(id string) func (conn common.DynamoDBConnection) (out StrategyCommunity, err error) {
	return func (conn common.DynamoDBConnection) (out StrategyCommunity, err error) {
		var outs []StrategyCommunity
		outs, err = ReadOrEmpty(id)(conn)
		if err == nil && len(outs) == 0 {
			err = fmt.Errorf("Not found id==%s in %s\n", id, TableName(conn.ClientID))
		}
		if len(outs) > 0 {
			out = outs[0]
		}
		return
	}
}


// ReadUnsafe reads the StrategyCommunity. Panics in case of any errors
func ReadUnsafe(id string) func (conn common.DynamoDBConnection) StrategyCommunity {
	return func (conn common.DynamoDBConnection) StrategyCommunity {
		out, err2 := Read(id)(conn)
		core.ErrorHandler(err2, "daos/StrategyCommunity", fmt.Sprintf("Error reading id==%s in %s\n", id, TableName(conn.ClientID)))
		return out
	}
}


// ReadOrEmpty reads StrategyCommunity
func ReadOrEmpty(id string) func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
	return func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
       out, err = ReadOrEmptyIncludingInactive(id)(conn)
       
       
		return
	}
}


// ReadOrEmptyUnsafe reads the StrategyCommunity. Panics in case of any errors
func ReadOrEmptyUnsafe(id string) func (conn common.DynamoDBConnection) []StrategyCommunity {
	return func (conn common.DynamoDBConnection) []StrategyCommunity {
		out, err2 := ReadOrEmpty(id)(conn)
		core.ErrorHandler(err2, "daos/StrategyCommunity", fmt.Sprintf("Error while reading id==%s in %s\n", id, TableName(conn.ClientID)))
		return out
	}
}


// ReadOrEmptyIncludingInactive reads StrategyCommunity
func ReadOrEmptyIncludingInactive(id string) func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
	return func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
		var outOrEmpty StrategyCommunity
		ids := idParams(id)
		var found bool
		found, err = conn.Dynamo.GetItemOrEmptyFromTable(TableName(conn.ClientID), ids, &outOrEmpty)
		if found {
			if outOrEmpty.ID == id {
				out = append(out, outOrEmpty)
			} else {
				err = fmt.Errorf("Requested ids: id==%s are different from the found ones: id==%s", id, outOrEmpty.ID) // unexpected error: found ids != ids
			}
		}
		err = errors.Wrapf(err, "StrategyCommunity DAO.ReadOrEmpty(id = %v) couldn't GetItem in table %s", ids, TableName(conn.ClientID))
		return
	}
}


// ReadOrEmptyIncludingInactiveUnsafe reads the StrategyCommunity. Panics in case of any errors
func ReadOrEmptyIncludingInactiveUnsafeIncludingInactive(id string) func (conn common.DynamoDBConnection) []StrategyCommunity {
	return func (conn common.DynamoDBConnection) []StrategyCommunity {
		out, err2 := ReadOrEmptyIncludingInactive(id)(conn)
		core.ErrorHandler(err2, "daos/StrategyCommunity", fmt.Sprintf("Error while reading id==%s in %s\n", id, TableName(conn.ClientID)))
		return out
	}
}


// CreateOrUpdate saves the StrategyCommunity regardless of if it exists.
func CreateOrUpdate(strategyCommunity StrategyCommunity) common.ConnectionProc {
	return func (conn common.DynamoDBConnection) (err error) {
		strategyCommunity.ModifiedAt = core.CurrentRFCTimestamp()
	if strategyCommunity.CreatedAt == "" { strategyCommunity.CreatedAt = strategyCommunity.ModifiedAt }
	
		var olds []StrategyCommunity
		olds, err = ReadOrEmpty(strategyCommunity.ID)(conn)
		err = errors.Wrapf(err, "StrategyCommunity DAO.CreateOrUpdate(id = id==%s) couldn't ReadOrEmpty", strategyCommunity.ID)
		if err == nil {
			if len(olds) == 0 {
				err = Create(strategyCommunity)(conn)
				err = errors.Wrapf(err, "StrategyCommunity DAO.CreateOrUpdate couldn't Create in table %s", TableName(conn.ClientID))
			} else {
				emptyFields, ok := strategyCommunity.CollectEmptyFields()
				if ok {
					old := olds[0]
					strategyCommunity.CreatedAt  = old.CreatedAt
					strategyCommunity.ModifiedAt = core.CurrentRFCTimestamp()
					key := idParams(old.ID)
					expr, exprAttributes, names := updateExpression(strategyCommunity, old)
					input := dynamodb.UpdateItemInput{
						ExpressionAttributeValues: exprAttributes,
						TableName:                 aws.String(TableName(conn.ClientID)),
						Key:                       key,
						ReturnValues:              aws.String("UPDATED_NEW"),
						UpdateExpression:          aws.String(expr),
					}
					if names != nil { input.ExpressionAttributeNames = *names } // workaround for a pointer to an empty slice
					if  len(exprAttributes) > 0 { // if there some changes
						err = conn.Dynamo.UpdateItemInternal(input)
					} else {
						// WARN: no changes.
					}
					err = errors.Wrapf(err, "StrategyCommunity DAO.CreateOrUpdate(id = %v) couldn't UpdateTableEntry in table %s, expression='%s'", key, TableName(conn.ClientID), expr)
				} else {
					err = fmt.Errorf("Cannot update entity with empty required fields: %v", emptyFields)
				}
			}
		}
		return 
	}
}


// CreateOrUpdateUnsafe saves the StrategyCommunity regardless of if it exists.
func CreateOrUpdateUnsafe(strategyCommunity StrategyCommunity) func (conn common.DynamoDBConnection) {
	return func (conn common.DynamoDBConnection) {
		err2 := CreateOrUpdate(strategyCommunity)(conn)
		core.ErrorHandler(err2, "daos/StrategyCommunity", fmt.Sprintf("could not create or update %v in %s\n", strategyCommunity, TableName(conn.ClientID)))
	}
}


// Delete removes StrategyCommunity from db
func Delete(id string) func (conn common.DynamoDBConnection) error {
	return func (conn common.DynamoDBConnection) error {
		return conn.Dynamo.DeleteEntry(TableName(conn.ClientID), idParams(id))
	}
}


// DeleteUnsafe deletes StrategyCommunity and panics in case of errors.
func DeleteUnsafe(id string) func (conn common.DynamoDBConnection) {
	return func (conn common.DynamoDBConnection) {
		err2 := Delete(id)(conn)
		core.ErrorHandler(err2, "daos/StrategyCommunity", fmt.Sprintf("Could not delete id==%s in %s\n", id, TableName(conn.ClientID)))
	}
}


func ReadByPlatformIDChannelCreated(platformID common.PlatformID, channelCreated int) func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
	return func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
		var instances []StrategyCommunity
		err = conn.Dynamo.QueryTableWithIndex(TableName(conn.ClientID), awsutils.DynamoIndexExpression{
			IndexName: "PlatformIDChannelCreatedIndex",
			Condition: "platform_id = :a0 and channel_created = :a1",
			Attributes: map[string]interface{}{
				":a0": platformID,
			":a1": channelCreated,
			},
		}, map[string]string{}, true, -1, &instances)
		out = instances
		return
	}
}


func ReadByPlatformIDChannelCreatedUnsafe(platformID common.PlatformID, channelCreated int) func (conn common.DynamoDBConnection) (out []StrategyCommunity) {
	return func (conn common.DynamoDBConnection) (out []StrategyCommunity) {
		out, err2 := ReadByPlatformIDChannelCreated(platformID, channelCreated)(conn)
		core.ErrorHandler(err2, "daos/StrategyCommunity", fmt.Sprintf("Could not query PlatformIDChannelCreatedIndex on %s table\n", TableName(conn.ClientID)))
		return
	}
}


func ReadByPlatformID(platformID common.PlatformID) func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
	return func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
		var instances []StrategyCommunity
		err = conn.Dynamo.QueryTableWithIndex(TableName(conn.ClientID), awsutils.DynamoIndexExpression{
			IndexName: "PlatformIDIndex",
			Condition: "platform_id = :a0",
			Attributes: map[string]interface{}{
				":a0": platformID,
			},
		}, map[string]string{}, true, -1, &instances)
		out = instances
		return
	}
}


func ReadByPlatformIDUnsafe(platformID common.PlatformID) func (conn common.DynamoDBConnection) (out []StrategyCommunity) {
	return func (conn common.DynamoDBConnection) (out []StrategyCommunity) {
		out, err2 := ReadByPlatformID(platformID)(conn)
		core.ErrorHandler(err2, "daos/StrategyCommunity", fmt.Sprintf("Could not query PlatformIDIndex on %s table\n", TableName(conn.ClientID)))
		return
	}
}


func ReadByChannelID(channelID string) func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
	return func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
		var instances []StrategyCommunity
		err = conn.Dynamo.QueryTableWithIndex(TableName(conn.ClientID), awsutils.DynamoIndexExpression{
			IndexName: "ChannelIDIndex",
			Condition: "channel_id = :a0",
			Attributes: map[string]interface{}{
				":a0": channelID,
			},
		}, map[string]string{}, true, -1, &instances)
		out = instances
		return
	}
}


func ReadByChannelIDUnsafe(channelID string) func (conn common.DynamoDBConnection) (out []StrategyCommunity) {
	return func (conn common.DynamoDBConnection) (out []StrategyCommunity) {
		out, err2 := ReadByChannelID(channelID)(conn)
		core.ErrorHandler(err2, "daos/StrategyCommunity", fmt.Sprintf("Could not query ChannelIDIndex on %s table\n", TableName(conn.ClientID)))
		return
	}
}


func ReadByHashKeyPlatformID(platformID common.PlatformID) func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
	return func (conn common.DynamoDBConnection) (out []StrategyCommunity, err error) {
		var instances []StrategyCommunity
		err = conn.Dynamo.QueryTableWithIndex(TableName(conn.ClientID), awsutils.DynamoIndexExpression{
			IndexName: string(PlatformIDChannelCreatedIndex),
			Condition: "platform_id = :a",
			Attributes: map[string]interface{}{
				":a" : platformID,
			},
		}, map[string]string{}, true, -1, &instances)
		out = instances
		return
	}
}


func ReadByHashKeyPlatformIDUnsafe(platformID common.PlatformID) func (conn common.DynamoDBConnection) (out []StrategyCommunity) {
	return func (conn common.DynamoDBConnection) (out []StrategyCommunity) {
		out, err2 := ReadByHashKeyPlatformID(platformID)(conn)
		core.ErrorHandler(err2, "daos/StrategyCommunity", fmt.Sprintf("Could not query PlatformIDChannelCreatedIndex on %s table\n", TableName(conn.ClientID)))
		return
	}
}

