package strategyInitiative
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.
import (
	"github.com/aws/aws-sdk-go/aws"
	awsutils "github.com/adaptiveteam/adaptive/aws-utils-go"
	common "github.com/adaptiveteam/adaptive/daos/common"
	core "github.com/adaptiveteam/adaptive/core-utils-go"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/pkg/errors"
	"fmt"
)


// Create saves the StrategyInitiative.
func Create(strategyInitiative StrategyInitiative) common.ConnectionProc {
	return func (conn common.DynamoDBConnection) (err error) {
		emptyFields, ok := strategyInitiative.CollectEmptyFields()
		if ok {
			strategyInitiative.ModifiedAt = core.CurrentRFCTimestamp()
	strategyInitiative.CreatedAt = strategyInitiative.ModifiedAt
	
			err = conn.Dynamo.PutTableEntry(strategyInitiative, TableName(conn.ClientID))
		} else {
			err = fmt.Errorf("Cannot create entity with empty fields: %v", emptyFields)
		}
		return
	}
}


// CreateUnsafe saves the StrategyInitiative.
func CreateUnsafe(strategyInitiative StrategyInitiative) func (conn common.DynamoDBConnection) {
	return func (conn common.DynamoDBConnection) {
		err2 := Create(strategyInitiative)(conn)
		core.ErrorHandler(err2, "daos/StrategyInitiative", fmt.Sprintf("Could not create platformID==%s, id==%s in %s\n", strategyInitiative.PlatformID, strategyInitiative.ID, TableName(conn.ClientID)))
	}
}


// Read reads StrategyInitiative
func Read(platformID common.PlatformID, id string) func (conn common.DynamoDBConnection) (out StrategyInitiative, err error) {
	return func (conn common.DynamoDBConnection) (out StrategyInitiative, err error) {
		var outs []StrategyInitiative
		outs, err = ReadOrEmpty(platformID, id)(conn)
		if err == nil && len(outs) == 0 {
			err = fmt.Errorf("Not found platformID==%s, id==%s in %s\n", platformID, id, TableName(conn.ClientID))
		}
		if len(outs) > 0 {
			out = outs[0]
		}
		return
	}
}


// ReadUnsafe reads the StrategyInitiative. Panics in case of any errors
func ReadUnsafe(platformID common.PlatformID, id string) func (conn common.DynamoDBConnection) StrategyInitiative {
	return func (conn common.DynamoDBConnection) StrategyInitiative {
		out, err2 := Read(platformID, id)(conn)
		core.ErrorHandler(err2, "daos/StrategyInitiative", fmt.Sprintf("Error reading platformID==%s, id==%s in %s\n", platformID, id, TableName(conn.ClientID)))
		return out
	}
}


// ReadOrEmpty reads StrategyInitiative
func ReadOrEmpty(platformID common.PlatformID, id string) func (conn common.DynamoDBConnection) (out []StrategyInitiative, err error) {
	return func (conn common.DynamoDBConnection) (out []StrategyInitiative, err error) {
		var outOrEmpty StrategyInitiative
		ids := idParams(platformID, id)
		var found bool
		found, err = conn.Dynamo.GetItemOrEmptyFromTable(TableName(conn.ClientID), ids, &outOrEmpty)
		if found {
			if outOrEmpty.PlatformID == platformID && outOrEmpty.ID == id {
				out = append(out, outOrEmpty)
			} else {
				err = fmt.Errorf("Requested ids: platformID==%s, id==%s are different from the found ones: platformID==%s, id==%s", platformID, id, outOrEmpty.PlatformID, outOrEmpty.ID) // unexpected error: found ids != ids
			}
		}
		err = errors.Wrapf(err, "StrategyInitiative DAO.ReadOrEmpty(id = %v) couldn't GetItem in table %s", ids, TableName(conn.ClientID))
		return
	}
}


// ReadOrEmptyUnsafe reads the StrategyInitiative. Panics in case of any errors
func ReadOrEmptyUnsafe(platformID common.PlatformID, id string) func (conn common.DynamoDBConnection) []StrategyInitiative {
	return func (conn common.DynamoDBConnection) []StrategyInitiative {
		out, err2 := ReadOrEmpty(platformID, id)(conn)
		core.ErrorHandler(err2, "daos/StrategyInitiative", fmt.Sprintf("Error while reading platformID==%s, id==%s in %s\n", platformID, id, TableName(conn.ClientID)))
		return out
	}
}


// CreateOrUpdate saves the StrategyInitiative regardless of if it exists.
func CreateOrUpdate(strategyInitiative StrategyInitiative) common.ConnectionProc {
	return func (conn common.DynamoDBConnection) (err error) {
		strategyInitiative.ModifiedAt = core.CurrentRFCTimestamp()
	if strategyInitiative.CreatedAt == "" { strategyInitiative.CreatedAt = strategyInitiative.ModifiedAt }
	
		var olds []StrategyInitiative
		olds, err = ReadOrEmpty(strategyInitiative.PlatformID, strategyInitiative.ID)(conn)
		err = errors.Wrapf(err, "StrategyInitiative DAO.CreateOrUpdate(id = platformID==%s, id==%s) couldn't ReadOrEmpty", strategyInitiative.PlatformID, strategyInitiative.ID)
		if err == nil {
			if len(olds) == 0 {
				err = Create(strategyInitiative)(conn)
				err = errors.Wrapf(err, "StrategyInitiative DAO.CreateOrUpdate couldn't Create in table %s", TableName(conn.ClientID))
			} else {
				emptyFields, ok := strategyInitiative.CollectEmptyFields()
				if ok {
					old := olds[0]
					strategyInitiative.CreatedAt  = old.CreatedAt
					strategyInitiative.ModifiedAt = core.CurrentRFCTimestamp()
					key := idParams(old.PlatformID, old.ID)
					expr, exprAttributes, names := updateExpression(strategyInitiative, old)
					input := dynamodb.UpdateItemInput{
						ExpressionAttributeValues: exprAttributes,
						TableName:                 aws.String(TableName(conn.ClientID)),
						Key:                       key,
						ReturnValues:              aws.String("UPDATED_NEW"),
						UpdateExpression:          aws.String(expr),
					}
					if names != nil { input.ExpressionAttributeNames = *names } // workaround for a pointer to an empty slice
					if  len(exprAttributes) > 0 { // if there some changes
						err = conn.Dynamo.UpdateItemInternal(input)
					} else {
						// WARN: no changes.
					}
					err = errors.Wrapf(err, "StrategyInitiative DAO.CreateOrUpdate(id = %v) couldn't UpdateTableEntry in table %s, expression='%s'", key, TableName(conn.ClientID), expr)
				} else {
					err = fmt.Errorf("Cannot update entity with empty required fields: %v", emptyFields)
				}
			}
		}
		return 
	}
}


// CreateOrUpdateUnsafe saves the StrategyInitiative regardless of if it exists.
func CreateOrUpdateUnsafe(strategyInitiative StrategyInitiative) func (conn common.DynamoDBConnection) {
	return func (conn common.DynamoDBConnection) {
		err2 := CreateOrUpdate(strategyInitiative)(conn)
		core.ErrorHandler(err2, "daos/StrategyInitiative", fmt.Sprintf("could not create or update %v in %s\n", strategyInitiative, TableName(conn.ClientID)))
	}
}


// Delete removes StrategyInitiative from db
func Delete(platformID common.PlatformID, id string) func (conn common.DynamoDBConnection) error {
	return func (conn common.DynamoDBConnection) error {
		return conn.Dynamo.DeleteEntry(TableName(conn.ClientID), idParams(platformID, id))
	}
}


// DeleteUnsafe deletes StrategyInitiative and panics in case of errors.
func DeleteUnsafe(platformID common.PlatformID, id string) func (conn common.DynamoDBConnection) {
	return func (conn common.DynamoDBConnection) {
		err2 := Delete(platformID, id)(conn)
		core.ErrorHandler(err2, "daos/StrategyInitiative", fmt.Sprintf("Could not delete platformID==%s, id==%s in %s\n", platformID, id, TableName(conn.ClientID)))
	}
}


func ReadByPlatformID(platformID common.PlatformID) func (conn common.DynamoDBConnection) (out []StrategyInitiative, err error) {
	return func (conn common.DynamoDBConnection) (out []StrategyInitiative, err error) {
		var instances []StrategyInitiative
		err = conn.Dynamo.QueryTableWithIndex(TableName(conn.ClientID), awsutils.DynamoIndexExpression{
			IndexName: "PlatformIDIndex",
			Condition: "platform_id = :a0",
			Attributes: map[string]interface{}{
				":a0": platformID,
			},
		}, map[string]string{}, true, -1, &instances)
		out = instances
		return
	}
}


func ReadByPlatformIDUnsafe(platformID common.PlatformID) func (conn common.DynamoDBConnection) (out []StrategyInitiative) {
	return func (conn common.DynamoDBConnection) (out []StrategyInitiative) {
		out, err2 := ReadByPlatformID(platformID)(conn)
		core.ErrorHandler(err2, "daos/StrategyInitiative", fmt.Sprintf("Could not query PlatformIDIndex on %s table\n", TableName(conn.ClientID)))
		return
	}
}


func ReadByInitiativeCommunityID(initiativeCommunityID string) func (conn common.DynamoDBConnection) (out []StrategyInitiative, err error) {
	return func (conn common.DynamoDBConnection) (out []StrategyInitiative, err error) {
		var instances []StrategyInitiative
		err = conn.Dynamo.QueryTableWithIndex(TableName(conn.ClientID), awsutils.DynamoIndexExpression{
			IndexName: "InitiativeCommunityIDIndex",
			Condition: "initiative_community_id = :a0",
			Attributes: map[string]interface{}{
				":a0": initiativeCommunityID,
			},
		}, map[string]string{}, true, -1, &instances)
		out = instances
		return
	}
}


func ReadByInitiativeCommunityIDUnsafe(initiativeCommunityID string) func (conn common.DynamoDBConnection) (out []StrategyInitiative) {
	return func (conn common.DynamoDBConnection) (out []StrategyInitiative) {
		out, err2 := ReadByInitiativeCommunityID(initiativeCommunityID)(conn)
		core.ErrorHandler(err2, "daos/StrategyInitiative", fmt.Sprintf("Could not query InitiativeCommunityIDIndex on %s table\n", TableName(conn.ClientID)))
		return
	}
}

