package coachingRelationship
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.

type FieldName string
const (
	CoachQuarterYear FieldName = "coach_quarter_year"
	CoacheeQuarterYear FieldName = "coachee_quarter_year"
	Coachee FieldName = "coachee"
	Quarter FieldName = "quarter"
	Year FieldName = "year"
	CoachRequested FieldName = "coach_requested"
	CoacheeRequested FieldName = "coachee_requested"
)

type IndexName string
const (
	CoachQuarterYearIndex IndexName = "CoachQuarterYearIndex"
	QuarterYearIndex IndexName = "QuarterYearIndex"
	CoacheeQuarterYearIndex IndexName = "CoacheeQuarterYearIndex"
)
