package strategyObjective
// This file has been automatically generated by `adaptive-platform/scripts`
// The changes will be overridden by the next automatic generation.
import (
	"github.com/adaptiveteam/adaptive-utils-go/models"
	"time"
	awsutils "github.com/adaptiveteam/aws-utils-go"
	common "github.com/adaptiveteam/adaptive/daos/common"
	core "github.com/adaptiveteam/adaptive/core-utils-go"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/pkg/errors"
	"fmt"
	"strings"
)

type StrategyObjectiveType string

type StrategyObjective struct  {
	// hash
	ID string `json:"id"`
	// range key
	PlatformID models.PlatformID `json:"platform_id"`
	Name string `json:"name"`
	Description string `json:"description"`
	AsMeasuredBy string `json:"as_measured_by"`
	Targets string `json:"targets"`
	ObjectiveType StrategyObjectiveType `json:"objective_type"`
	Advocate string `json:"advocate"`
	// community id not require d for customer/financial objectives
	CapabilityCommunityIDs []string `json:"capability_community_i_ds"`
	ExpectedEndDate string `json:"expected_end_date"`
	CreatedBy string `json:"created_by"`
	// Automatically maintained field
	CreatedAt string `json:"created_at"`
	// Automatically maintained field
	ModifiedAt string `json:"modified_at"`
}

// CollectEmptyFields returns entity field names that are empty.
// It also returns the boolean ok-flag if the list is empty.
func (strategyObjective StrategyObjective)CollectEmptyFields() (emptyFields []string, ok bool) {
	if strategyObjective.ID == "" { emptyFields = append(emptyFields, "ID")}
	if strategyObjective.PlatformID == "" { emptyFields = append(emptyFields, "PlatformID")}
	if strategyObjective.Name == "" { emptyFields = append(emptyFields, "Name")}
	if strategyObjective.Description == "" { emptyFields = append(emptyFields, "Description")}
	if strategyObjective.AsMeasuredBy == "" { emptyFields = append(emptyFields, "AsMeasuredBy")}
	if strategyObjective.Targets == "" { emptyFields = append(emptyFields, "Targets")}
	if strategyObjective.Advocate == "" { emptyFields = append(emptyFields, "Advocate")}
	if strategyObjective.CapabilityCommunityIDs == nil { emptyFields = append(emptyFields, "CapabilityCommunityIDs")}
	if strategyObjective.ExpectedEndDate == "" { emptyFields = append(emptyFields, "ExpectedEndDate")}
	if strategyObjective.CreatedBy == "" { emptyFields = append(emptyFields, "CreatedBy")}
	ok = len(emptyFields) == 0
	return
}

type DAO interface {
	Create(strategyObjective StrategyObjective) error
	CreateUnsafe(strategyObjective StrategyObjective)
	Read(id string) (strategyObjective StrategyObjective, err error)
	ReadUnsafe(id string) (strategyObjective StrategyObjective)
	ReadOrEmpty(id string) (strategyObjective []StrategyObjective, err error)
	ReadOrEmptyUnsafe(id string) (strategyObjective []StrategyObjective)
	CreateOrUpdate(strategyObjective StrategyObjective) error
	CreateOrUpdateUnsafe(strategyObjective StrategyObjective)
	Delete(id string) error
	DeleteUnsafe(id string)
	ReadByIDPlatformID(id string, platformID models.PlatformID) (strategyObjective []StrategyObjective, err error)
	ReadByIDPlatformIDUnsafe(id string, platformID models.PlatformID) (strategyObjective []StrategyObjective)
	ReadByPlatformID(platformID models.PlatformID) (strategyObjective []StrategyObjective, err error)
	ReadByPlatformIDUnsafe(platformID models.PlatformID) (strategyObjective []StrategyObjective)
}

// DAOImpl - a container for all information needed to access a DynamoDB table
type DAOImpl struct {
	Dynamo    *awsutils.DynamoRequest `json:"dynamo"`
	Namespace string                  `json:"namespace"`
	Name      string                  `json:"name"`
}

// NewDAO creates an instance of DAO that will provide access to the table
func NewDAO(dynamo *awsutils.DynamoRequest, namespace, clientID string) DAO {
	if clientID == "" { panic("Cannot create DAO without clientID") }
	return DAOImpl{Dynamo: dynamo, Namespace: namespace, 
		Name: clientID + "_strategy_objective",
	}
}

// NewDAOByTableName creates an instance of DAO that will provide access to the table
func NewDAOByTableName(dynamo *awsutils.DynamoRequest, namespace, tableName string) DAO {
	if tableName == "" { panic("Cannot create DAO without tableName") }
	return DAOImpl{Dynamo: dynamo, Namespace: namespace, 
		Name: tableName,
	}
}

// Create saves the StrategyObjective.
func (d DAOImpl) Create(strategyObjective StrategyObjective) error {
	emptyFields, ok := strategyObjective.CollectEmptyFields()
	if !ok {return fmt.Errorf("Cannot create entity with empty fields: %v", emptyFields)}
	strategyObjective.ModifiedAt = core.TimestampLayout.Format(time.Now())
	strategyObjective.CreatedAt = strategyObjective.ModifiedAt
	return d.Dynamo.PutTableEntry(strategyObjective, d.Name)
}


// CreateUnsafe saves the StrategyObjective.
func (d DAOImpl) CreateUnsafe(strategyObjective StrategyObjective) {
	err := d.Create(strategyObjective)
	core.ErrorHandler(err, d.Namespace, fmt.Sprintf("Could not create id==%s in %s\n", strategyObjective.ID, d.Name))
}


// Read reads StrategyObjective
func (d DAOImpl) Read(id string) (out StrategyObjective, err error) {
	var outs []StrategyObjective
	outs, err = d.ReadOrEmpty(id)
	if err == nil && len(outs) == 0 {
		err = fmt.Errorf("Not found id==%s in %s\n", id, d.Name)
	}
	return
}


// ReadUnsafe reads the StrategyObjective. Panics in case of any errors
func (d DAOImpl) ReadUnsafe(id string) StrategyObjective {
	out, err := d.Read(id)
	core.ErrorHandler(err, d.Namespace, fmt.Sprintf("Error reading id==%s in %s\n", id, d.Name))
	return out
}


// ReadOrEmpty reads StrategyObjective
func (d DAOImpl) ReadOrEmpty(id string) (out []StrategyObjective, err error) {
	var outOrEmpty StrategyObjective
	ids := idParams(id)
	err = d.Dynamo.QueryTable(d.Name, ids, &outOrEmpty)
	if outOrEmpty.ID == id {
		out = append(out, outOrEmpty)
	}
	err = errors.Wrapf(err, "StrategyObjective DAO.ReadOrEmpty(id = %v) couldn't GetItem in table %s", ids, d.Name)
	return
}


// ReadOrEmptyUnsafe reads the StrategyObjective. Panics in case of any errors
func (d DAOImpl) ReadOrEmptyUnsafe(id string) []StrategyObjective {
	out, err := d.ReadOrEmpty(id)
	core.ErrorHandler(err, d.Namespace, fmt.Sprintf("Error while reading id==%s in %s\n", id, d.Name))
	return out
}


// CreateOrUpdate saves the StrategyObjective regardless of if it exists.
func (d DAOImpl) CreateOrUpdate(strategyObjective StrategyObjective) (err error) {
	strategyObjective.ModifiedAt = core.TimestampLayout.Format(time.Now())
	if strategyObjective.CreatedAt == "" { strategyObjective.CreatedAt = strategyObjective.ModifiedAt }
	
	var olds []StrategyObjective
	olds, err = d.ReadOrEmpty(strategyObjective.ID)
	if err == nil {
		if len(olds) == 0 {
			err = d.Create(strategyObjective)
			err = errors.Wrapf(err, "StrategyObjective DAO.CreateOrUpdate couldn't Create in table %s", d.Name)
		} else {
			old := olds[0]
			strategyObjective.ModifiedAt = core.TimestampLayout.Format(time.Now())
ids := idParams(old.ID)
			err = d.Dynamo.UpdateTableEntry(
				allParams(strategyObjective, old),
				ids,
				updateExpression(strategyObjective, old),
				d.Name,
			)
			err = errors.Wrapf(err, "StrategyObjective DAO.CreateOrUpdate(id = %v) couldn't UpdateTableEntry in table %s", ids, d.Name)
		}
	}
	return 
}


// CreateOrUpdateUnsafe saves the StrategyObjective regardless of if it exists.
func (d DAOImpl) CreateOrUpdateUnsafe(strategyObjective StrategyObjective) {
	err := d.CreateOrUpdate(strategyObjective)
	core.ErrorHandler(err, d.Namespace, fmt.Sprintf("could not create or update %v in %s\n", strategyObjective, d.Name))
}


// Delete removes StrategyObjective from db
func (d DAOImpl)Delete(id string) error {
	return d.Dynamo.DeleteEntry(d.Name, idParams(id))
}


// DeleteUnsafe deletes StrategyObjective and panics in case of errors.
func (d DAOImpl)DeleteUnsafe(id string) {
	err := d.Delete(id)
	core.ErrorHandler(err, d.Namespace, fmt.Sprintf("Could not delete id==%s in %s\n", id, d.Name))
}


func (d DAOImpl)ReadByIDPlatformID(id string, platformID models.PlatformID) (out []StrategyObjective, err error) {
	var instances []StrategyObjective
	err = d.Dynamo.QueryTableWithIndex(d.Name, awsutils.DynamoIndexExpression{
		IndexName: "IDPlatformIDIndex",
		Condition: "id = :a0 and platform_id = :a1",
		Attributes: map[string]interface{}{
			":a0": id,
			":a1": platformID,
		},
	}, map[string]string{}, true, -1, &instances)
	out = instances
	return
}


func (d DAOImpl)ReadByIDPlatformIDUnsafe(id string, platformID models.PlatformID) (out []StrategyObjective) {
	out, err := d.ReadByIDPlatformID(id, platformID)
	core.ErrorHandler(err, d.Namespace, fmt.Sprintf("Could not query IDPlatformIDIndex on %s table\n", d.Name))
	return
}


func (d DAOImpl)ReadByPlatformID(platformID models.PlatformID) (out []StrategyObjective, err error) {
	var instances []StrategyObjective
	err = d.Dynamo.QueryTableWithIndex(d.Name, awsutils.DynamoIndexExpression{
		IndexName: "PlatformIDIndex",
		Condition: "platform_id = :a0",
		Attributes: map[string]interface{}{
			":a0": platformID,
		},
	}, map[string]string{}, true, -1, &instances)
	out = instances
	return
}


func (d DAOImpl)ReadByPlatformIDUnsafe(platformID models.PlatformID) (out []StrategyObjective) {
	out, err := d.ReadByPlatformID(platformID)
	core.ErrorHandler(err, d.Namespace, fmt.Sprintf("Could not query PlatformIDIndex on %s table\n", d.Name))
	return
}

func idParams(id string) map[string]*dynamodb.AttributeValue {
	params := map[string]*dynamodb.AttributeValue {
		"id": common.DynS(id),
	}
	return params
}
func allParams(strategyObjective StrategyObjective, old StrategyObjective) (params map[string]*dynamodb.AttributeValue) {
	
		params = map[string]*dynamodb.AttributeValue{}
		if strategyObjective.ID != old.ID { params["a0"] = common.DynS(strategyObjective.ID) }
		if strategyObjective.PlatformID != old.PlatformID { params["a1"] = common.DynS(string(strategyObjective.PlatformID)) }
		if strategyObjective.Name != old.Name { params["a2"] = common.DynS(strategyObjective.Name) }
		if strategyObjective.Description != old.Description { params["a3"] = common.DynS(strategyObjective.Description) }
		if strategyObjective.AsMeasuredBy != old.AsMeasuredBy { params["a4"] = common.DynS(strategyObjective.AsMeasuredBy) }
		if strategyObjective.Targets != old.Targets { params["a5"] = common.DynS(strategyObjective.Targets) }
		if strategyObjective.ObjectiveType != old.ObjectiveType { params["a6"] = common.DynS(string(strategyObjective.ObjectiveType)) }
		if strategyObjective.Advocate != old.Advocate { params["a7"] = common.DynS(strategyObjective.Advocate) }
		if !common.StringArraysEqual(strategyObjective.CapabilityCommunityIDs, old.CapabilityCommunityIDs) { params["a8"] = common.DynSS(strategyObjective.CapabilityCommunityIDs) }
		if strategyObjective.ExpectedEndDate != old.ExpectedEndDate { params["a9"] = common.DynS(strategyObjective.ExpectedEndDate) }
		if strategyObjective.CreatedBy != old.CreatedBy { params["a10"] = common.DynS(strategyObjective.CreatedBy) }
		if strategyObjective.CreatedAt != old.CreatedAt { params["a11"] = common.DynS(strategyObjective.CreatedAt) }
		if strategyObjective.ModifiedAt != old.ModifiedAt { params["a12"] = common.DynS(strategyObjective.ModifiedAt) }
	return
}
func updateExpression(strategyObjective StrategyObjective, old StrategyObjective) string {
	var updateParts []string
	
		
			
		if strategyObjective.ID != old.ID { updateParts = append(updateParts, "id = :a0") }
		if strategyObjective.PlatformID != old.PlatformID { updateParts = append(updateParts, "platform_id = :a1") }
		if strategyObjective.Name != old.Name { updateParts = append(updateParts, "#name = :a2") }
		if strategyObjective.Description != old.Description { updateParts = append(updateParts, "description = :a3") }
		if strategyObjective.AsMeasuredBy != old.AsMeasuredBy { updateParts = append(updateParts, "as_measured_by = :a4") }
		if strategyObjective.Targets != old.Targets { updateParts = append(updateParts, "targets = :a5") }
		if strategyObjective.ObjectiveType != old.ObjectiveType { updateParts = append(updateParts, "objective_type = :a6") }
		if strategyObjective.Advocate != old.Advocate { updateParts = append(updateParts, "advocate = :a7") }
		if !common.StringArraysEqual(strategyObjective.CapabilityCommunityIDs, old.CapabilityCommunityIDs) { updateParts = append(updateParts, "capability_community_i_ds = :a8") }
		if strategyObjective.ExpectedEndDate != old.ExpectedEndDate { updateParts = append(updateParts, "expected_end_date = :a9") }
		if strategyObjective.CreatedBy != old.CreatedBy { updateParts = append(updateParts, "created_by = :a10") }
		if strategyObjective.CreatedAt != old.CreatedAt { updateParts = append(updateParts, "created_at = :a11") }
		if strategyObjective.ModifiedAt != old.ModifiedAt { updateParts = append(updateParts, "modified_at = :a12") }
	return strings.Join(updateParts, " and ")
}
