package contextAliasEntry
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.

type FieldName string
const (
	ApplicationAlias FieldName = "application_alias"
	Context FieldName = "context"
	BuildID FieldName = "build_id"
)
