package migration
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.

type FieldName string
const (
	PlatformID FieldName = "platform_id"
	MigrationID FieldName = "migration_id"
	SuccessCount FieldName = "success_count"
	FailuresCount FieldName = "failures_count"
)
