package styles

var Styles = map[string]string{
"Normal Font":             `"font":{"bold":false,"italic":false,"family":"Calibri","size":14,"color":"000000"}`,
"Link Font":               `"font":{"bold":false,"italic":true,"family":"Calibri","size":14,"color":"0000EE"}`,
"Italics Font":            `"font":{"bold":false,"italic":true,"family":"Calibri","size":14,"color":"000000"}`,
"Heading Font":            `"font":{"bold":true,"italic":false,"family":"Calibri","size":14,"color":"FFFFFF"}`,
"Rotated Heading Font":    `"font":{"bold":true,"italic":false,"family":"Calibri","size":14,"color":"FFFFFF"}`,
"Return Font":             `"font":{"bold":true,"italic":true,"family":"Calibri","size":14,"color":"0000EE"}`,
"Index Font":              `"font":{"bold":true,"italic":false,"family":"Calibri","size":14,"color":"FFFFFF"}`,
"Title Font":              `"font":{"bold":true,"italic":false,"family":"Calibri","size":24,"color":"FFFFFF"}`,
"Subtitle Font":           `"font":{"bold":true,"italic":false,"family":"Calibri","size":18,"color":"FFFFFF"}`,
"Closed Font":          `"font":{"bold":true,"italic":true,"family":"Calibri","size":14,"color":"FFFFFF"}`,
"Active Font":         `"font":{"bold":true,"italic":true,"family":"Calibri","size":14,"color":"000000"}`,
"Normal Background":       `"fill":{"type":"pattern","color":["FFFFFF"],"pattern":1}`,
"Instructions Background": `"fill":{"type":"pattern","color":["#F5F5F5"],"pattern":1}`,
"Return Background":       `"fill":{"type":"pattern","color":["#F2F4F4"],"pattern":1}`,
"Heading Background":      `"fill":{"type":"pattern","color":["000066"],"pattern":1}`,
"Horizontal Center":       `"alignment":{"horizontal":"center", "wrap_text":true}`,
"Vertical Center":         `"alignment":{"vertical":"center", "wrap_text":true}`,
"Rotated":                 `"alignment":{"vertical":"center", "horizontal":"center", "wrap_text":true, "text_rotation":90}`,
"Centered":                `"alignment":{"vertical":"center", "horizontal":"center", "wrap_text":true}`,
"Black Borders":           `"border":[{"type":"left","color":"000000","style":1},{"type":"top","color":"000000","style":1},{"type":"bottom","color":"000000","style":1},{"type":"right","color":"000000","style":1}]`,
"White Borders":           `"border":[{"type":"left","color":"FFFFFF","style":1},{"type":"top","color":"FFFFFF","style":1},{"type":"bottom","color":"FFFFFF","style":1},{"type":"right","color":"FFFFFF","style":1}]`,
"White Bottom Border":     `"border":[{"type":"bottom","color":"FFFFFF","style":2}]`,
"Off Track":               `"fill":{"type":"pattern","color":["ff0000"],"pattern":1}`,
"At Risk":                 `"fill":{"type":"pattern","color":["ffff00"],"pattern":1}`,
"On Track":                `"fill":{"type":"pattern","color":["00ff00"],"pattern":1}`,
"No Status":               `"fill":{"type":"pattern","color":["C0C0C0"],"pattern":1}`,
"Closed Background":     `"fill":{"type":"pattern","color":["000000"],"pattern":1}`,
"Active Background":   `"fill":{"type":"pattern","color":["C0C0C0"],"pattern":1}`,
"No":                      `"fill":{"type":"pattern","color":["ff0000"],"pattern":1}`,
"Yes":                     `"fill":{"type":"pattern","color":["00ff00"],"pattern":1}`,
}

