package objectiveTypeDictionary
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.
import (
	"time"
	"github.com/aws/aws-sdk-go/aws"
	awsutils "github.com/adaptiveteam/adaptive/aws-utils-go"
	common "github.com/adaptiveteam/adaptive/daos/common"
	core "github.com/adaptiveteam/adaptive/core-utils-go"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/pkg/errors"
	"fmt"
	"encoding/json"
	"strings"
)

type ObjectiveTypeDictionary struct  {
	// hash
	ID string `json:"id"`
	// range key
	PlatformID common.PlatformID `json:"platform_id"`
	Name string `json:"name"`
	Description string `json:"description"`
	// Automatically maintained field
	CreatedAt string `json:"created_at"`
	// Automatically maintained field
	ModifiedAt string `json:"modified_at,omitempty"`
	DeactivatedAt string `json:"deactivated_at,omitempty"`
}

// ObjectiveTypeDictionaryFilterActive removes deactivated values
func ObjectiveTypeDictionaryFilterActive(in []ObjectiveTypeDictionary) (res []ObjectiveTypeDictionary) {
	for _, i := range in {
		if i.DeactivatedOn == "" {
			res = append(res, i)
		}
	}
	return
}

// CollectEmptyFields returns entity field names that are empty.
// It also returns the boolean ok-flag if the list is empty.
func (objectiveTypeDictionary ObjectiveTypeDictionary)CollectEmptyFields() (emptyFields []string, ok bool) {
	if objectiveTypeDictionary.ID == "" { emptyFields = append(emptyFields, "ID")}
	if objectiveTypeDictionary.PlatformID == "" { emptyFields = append(emptyFields, "PlatformID")}
	if objectiveTypeDictionary.Name == "" { emptyFields = append(emptyFields, "Name")}
	if objectiveTypeDictionary.Description == "" { emptyFields = append(emptyFields, "Description")}
	ok = len(emptyFields) == 0
	return
}
// ToJSON returns json string
func (objectiveTypeDictionary ObjectiveTypeDictionary) ToJSON() (string, error) {
	b, err := json.Marshal(objectiveTypeDictionary)
	return string(b), err
}

type DAO interface {
	Create(objectiveTypeDictionary ObjectiveTypeDictionary) error
	CreateUnsafe(objectiveTypeDictionary ObjectiveTypeDictionary)
	Read(id string) (objectiveTypeDictionary ObjectiveTypeDictionary, err error)
	ReadUnsafe(id string) (objectiveTypeDictionary ObjectiveTypeDictionary)
	ReadOrEmpty(id string) (objectiveTypeDictionary []ObjectiveTypeDictionary, err error)
	ReadOrEmptyUnsafe(id string) (objectiveTypeDictionary []ObjectiveTypeDictionary)
	CreateOrUpdate(objectiveTypeDictionary ObjectiveTypeDictionary) error
	CreateOrUpdateUnsafe(objectiveTypeDictionary ObjectiveTypeDictionary)
	Deactivate(id string) error
	DeactivateUnsafe(id string)
	ReadByPlatformID(platformID common.PlatformID) (objectiveTypeDictionary []ObjectiveTypeDictionary, err error)
	ReadByPlatformIDUnsafe(platformID common.PlatformID) (objectiveTypeDictionary []ObjectiveTypeDictionary)
}

// DAOImpl - a container for all information needed to access a DynamoDB table
type DAOImpl struct {
	Dynamo    *awsutils.DynamoRequest `json:"dynamo"`
	Namespace string                  `json:"namespace"`
	Name      string                  `json:"name"`
}

// NewDAO creates an instance of DAO that will provide access to the table
func NewDAO(dynamo *awsutils.DynamoRequest, namespace, clientID string) DAO {
	if clientID == "" { panic("Cannot create DAO without clientID") }
	return DAOImpl{Dynamo: dynamo, Namespace: namespace, 
		Name: TableName(clientID),
	}
}

// NewDAOByTableName creates an instance of DAO that will provide access to the table
func NewDAOByTableName(dynamo *awsutils.DynamoRequest, namespace, tableName string) DAO {
	if tableName == "" { panic("Cannot create DAO without tableName") }
	return DAOImpl{Dynamo: dynamo, Namespace: namespace, 
		Name: tableName,
	}
}
func TableName(clientID string) string {
	return clientID + "_objective_type_dictionary"
}

// Create saves the ObjectiveTypeDictionary.
func (d DAOImpl) Create(objectiveTypeDictionary ObjectiveTypeDictionary) (err error) {
	emptyFields, ok := objectiveTypeDictionary.CollectEmptyFields()
	if ok {
		objectiveTypeDictionary.ModifiedAt = core.TimestampLayout.Format(time.Now())
	objectiveTypeDictionary.CreatedAt = objectiveTypeDictionary.ModifiedAt
	err = d.Dynamo.PutTableEntry(objectiveTypeDictionary, d.Name)
	} else {
		err = fmt.Errorf("Cannot create entity with empty fields: %v", emptyFields)
	}
	return
}


// CreateUnsafe saves the ObjectiveTypeDictionary.
func (d DAOImpl) CreateUnsafe(objectiveTypeDictionary ObjectiveTypeDictionary) {
	err2 := d.Create(objectiveTypeDictionary)
	core.ErrorHandler(err2, d.Namespace, fmt.Sprintf("Could not create id==%s in %s\n", objectiveTypeDictionary.ID, d.Name))
}


// Read reads ObjectiveTypeDictionary
func (d DAOImpl) Read(id string) (out ObjectiveTypeDictionary, err error) {
	var outs []ObjectiveTypeDictionary
	outs, err = d.ReadOrEmpty(id)
	if err == nil && len(outs) == 0 {
		err = fmt.Errorf("Not found id==%s in %s\n", id, d.Name)
	}
	if len(outs) > 0 {
		out = outs[0]
	}
	return
}


// ReadUnsafe reads the ObjectiveTypeDictionary. Panics in case of any errors
func (d DAOImpl) ReadUnsafe(id string) ObjectiveTypeDictionary {
	out, err2 := d.Read(id)
	core.ErrorHandler(err2, d.Namespace, fmt.Sprintf("Error reading id==%s in %s\n", id, d.Name))
	return out
}


// ReadOrEmpty reads ObjectiveTypeDictionary
func (d DAOImpl) ReadOrEmpty(id string) (out []ObjectiveTypeDictionary, err error) {
	var outOrEmpty ObjectiveTypeDictionary
	ids := idParams(id)
	var found bool
	found, err = d.Dynamo.GetItemOrEmptyFromTable(d.Name, ids, &outOrEmpty)
	if found {
		if outOrEmpty.ID == id {
			out = append(out, outOrEmpty)
		} else {
			err = fmt.Errorf("Requested ids: id==%s are different from the found ones: id==%s", id, outOrEmpty.ID) // unexpected error: found ids != ids
		}
	}
	err = errors.Wrapf(err, "ObjectiveTypeDictionary DAO.ReadOrEmpty(id = %v) couldn't GetItem in table %s", ids, d.Name)
	return
}


// ReadOrEmptyUnsafe reads the ObjectiveTypeDictionary. Panics in case of any errors
func (d DAOImpl) ReadOrEmptyUnsafe(id string) []ObjectiveTypeDictionary {
	out, err2 := d.ReadOrEmpty(id)
	core.ErrorHandler(err2, d.Namespace, fmt.Sprintf("Error while reading id==%s in %s\n", id, d.Name))
	return out
}


// CreateOrUpdate saves the ObjectiveTypeDictionary regardless of if it exists.
func (d DAOImpl) CreateOrUpdate(objectiveTypeDictionary ObjectiveTypeDictionary) (err error) {
	objectiveTypeDictionary.ModifiedAt = core.TimestampLayout.Format(time.Now())
	if objectiveTypeDictionary.CreatedAt == "" { objectiveTypeDictionary.CreatedAt = objectiveTypeDictionary.ModifiedAt }
	
	var olds []ObjectiveTypeDictionary
	olds, err = d.ReadOrEmpty(objectiveTypeDictionary.ID)
	err = errors.Wrapf(err, "ObjectiveTypeDictionary DAO.CreateOrUpdate(id = id==%s) couldn't ReadOrEmpty", objectiveTypeDictionary.ID)
	if err == nil {
		if len(olds) == 0 {
			err = d.Create(objectiveTypeDictionary)
			err = errors.Wrapf(err, "ObjectiveTypeDictionary DAO.CreateOrUpdate couldn't Create in table %s", d.Name)
		} else {
			emptyFields, ok := objectiveTypeDictionary.CollectEmptyFields()
			if ok {
				old := olds[0]
				objectiveTypeDictionary.ModifiedAt = core.TimestampLayout.Format(time.Now())

				key := idParams(old.ID)
				expr, exprAttributes, names := updateExpression(objectiveTypeDictionary, old)
				input := dynamodb.UpdateItemInput{
					ExpressionAttributeValues: exprAttributes,
					TableName:                 aws.String(d.Name),
					Key:                       key,
					ReturnValues:              aws.String("UPDATED_NEW"),
					UpdateExpression:          aws.String(expr),
				}
				if names != nil { input.ExpressionAttributeNames = *names } // workaround for a pointer to an empty slice
				if err == nil {
					err = d.Dynamo.UpdateItemInternal(input)
				}
				err = errors.Wrapf(err, "ObjectiveTypeDictionary DAO.CreateOrUpdate(id = %v) couldn't UpdateTableEntry in table %s, expression='%s'", key, d.Name, expr)
			} else {
				err = fmt.Errorf("Cannot update entity with empty required fields: %v", emptyFields)
			}
		}
	}
	return 
}


// CreateOrUpdateUnsafe saves the ObjectiveTypeDictionary regardless of if it exists.
func (d DAOImpl) CreateOrUpdateUnsafe(objectiveTypeDictionary ObjectiveTypeDictionary) {
	err2 := d.CreateOrUpdate(objectiveTypeDictionary)
	core.ErrorHandler(err2, d.Namespace, fmt.Sprintf("could not create or update %v in %s\n", objectiveTypeDictionary, d.Name))
}


// Deactivate "removes" ObjectiveTypeDictionary. 
// The mechanism is adding timestamp to `DeactivatedOn` field. 
// Then, if this field is not empty, the instance is considered to be "active"
func (d DAOImpl)Deactivate(id string) error {
	instance, err2 := d.Read(id)
	if err2 == nil {
		instance.DeactivatedOn = core.ISODateLayout.Format(time.Now())
		err2 = d.CreateOrUpdate(instance)
	}
	return err2
}


// DeactivateUnsafe "deletes" ObjectiveTypeDictionary and panics in case of errors.
func (d DAOImpl)DeactivateUnsafe(id string) {
	err2 := d.Deactivate(id)
	core.ErrorHandler(err2, d.Namespace, fmt.Sprintf("Could not deactivate id==%s in %s\n", id, d.Name))
}


func (d DAOImpl)ReadByPlatformID(platformID common.PlatformID) (out []ObjectiveTypeDictionary, err error) {
	var instances []ObjectiveTypeDictionary
	err = d.Dynamo.QueryTableWithIndex(d.Name, awsutils.DynamoIndexExpression{
		IndexName: "PlatformIDIndex",
		Condition: "platform_id = :a0",
		Attributes: map[string]interface{}{
			":a0": platformID,
		},
	}, map[string]string{}, true, -1, &instances)
	out = ObjectiveTypeDictionaryFilterActive(instances)
	return
}


func (d DAOImpl)ReadByPlatformIDUnsafe(platformID common.PlatformID) (out []ObjectiveTypeDictionary) {
	out, err2 := d.ReadByPlatformID(platformID)
	core.ErrorHandler(err2, d.Namespace, fmt.Sprintf("Could not query PlatformIDIndex on %s table\n", d.Name))
	return
}

func idParams(id string) map[string]*dynamodb.AttributeValue {
	params := map[string]*dynamodb.AttributeValue {
		"id": common.DynS(id),
	}
	return params
}
func allParams(objectiveTypeDictionary ObjectiveTypeDictionary, old ObjectiveTypeDictionary) (params map[string]*dynamodb.AttributeValue) {
	params = map[string]*dynamodb.AttributeValue{}
	if objectiveTypeDictionary.ID != old.ID { params[":a0"] = common.DynS(objectiveTypeDictionary.ID) }
	if objectiveTypeDictionary.PlatformID != old.PlatformID { params[":a1"] = common.DynS(string(objectiveTypeDictionary.PlatformID)) }
	if objectiveTypeDictionary.Name != old.Name { params[":a2"] = common.DynS(objectiveTypeDictionary.Name) }
	if objectiveTypeDictionary.Description != old.Description { params[":a3"] = common.DynS(objectiveTypeDictionary.Description) }
	if objectiveTypeDictionary.CreatedAt != old.CreatedAt { params[":a4"] = common.DynS(objectiveTypeDictionary.CreatedAt) }
	if objectiveTypeDictionary.ModifiedAt != old.ModifiedAt { params[":a5"] = common.DynS(objectiveTypeDictionary.ModifiedAt) }
	if objectiveTypeDictionary.DeactivatedAt != old.DeactivatedAt { params[":a6"] = common.DynS(objectiveTypeDictionary.DeactivatedAt) }
	return
}
func updateExpression(objectiveTypeDictionary ObjectiveTypeDictionary, old ObjectiveTypeDictionary) (expr string, params map[string]*dynamodb.AttributeValue, namesPtr *map[string]*string) {
	var updateParts []string
	params = map[string]*dynamodb.AttributeValue{}
	names := map[string]*string{}
	if objectiveTypeDictionary.ID != old.ID { updateParts = append(updateParts, "id = :a0"); params[":a0"] = common.DynS(objectiveTypeDictionary.ID);  }
	if objectiveTypeDictionary.PlatformID != old.PlatformID { updateParts = append(updateParts, "platform_id = :a1"); params[":a1"] = common.DynS(string(objectiveTypeDictionary.PlatformID));  }
	if objectiveTypeDictionary.Name != old.Name { updateParts = append(updateParts, "#name = :a2"); params[":a2"] = common.DynS(objectiveTypeDictionary.Name); fldName := "name"; names["#name"] = &fldName }
	if objectiveTypeDictionary.Description != old.Description { updateParts = append(updateParts, "description = :a3"); params[":a3"] = common.DynS(objectiveTypeDictionary.Description);  }
	if objectiveTypeDictionary.CreatedAt != old.CreatedAt { updateParts = append(updateParts, "created_at = :a4"); params[":a4"] = common.DynS(objectiveTypeDictionary.CreatedAt);  }
	if objectiveTypeDictionary.ModifiedAt != old.ModifiedAt { updateParts = append(updateParts, "modified_at = :a5"); params[":a5"] = common.DynS(objectiveTypeDictionary.ModifiedAt);  }
	if objectiveTypeDictionary.DeactivatedAt != old.DeactivatedAt { updateParts = append(updateParts, "deactivated_at = :a6"); params[":a6"] = common.DynS(objectiveTypeDictionary.DeactivatedAt);  }
	expr = "set " + strings.Join(updateParts, ", ")
	if len(names) == 0 { namesPtr = nil } else { namesPtr = &names } // workaround for ValidationException: ExpressionAttributeNames must not be empty
	return
}
