package objectiveTypeDictionary
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.

type FieldName string
const (
	ID FieldName = "id"
	PlatformID FieldName = "platform_id"
	Name FieldName = "name"
	Description FieldName = "description"
)

type IndexName string
const (
	PlatformIDIndex IndexName = "PlatformIDIndex"
)
