# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy-to-staging"
  deploy-to-staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Deploy staging branch
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
        TF_VAR_RDS_ENDPOINT: ${{ secrets.STAGING_TF_VAR_RDS_ENDPOINT }}
        TF_VAR_RDS_PASSWORD: ${{ secrets.STAGING_TF_VAR_RDS_PASSWORD }}
        TF_VAR_SLACK_CLIENT_ID: ${{ secrets.STAGING_TF_VAR_SLACK_CLIENT_ID }}
        TF_VAR_SLACK_CLIENT_SECRET: ${{ secrets.STAGING_TF_VAR_SLACK_CLIENT_SECRET }}
        TF_VAR_SLACK_SIGNING_SECRET: ${{ secrets.STAGING_TF_VAR_SLACK_SIGNING_SECRET }}
        ADAPTIVE_CLIENT_ID: staging
        TF_VAR_environment: staging
        TF_VAR_client_id: staging
        ORGANIZATION: staging
        AWS_DEFAULT_REGION: "us-east-1"
        AWS_REGION: us-east-1
        TF_VAR_profile: ""
        TF_VAR_aws_region: "us-east-1"
        TF_VAR_core_state_region: "us-east-1"
        TF_VAR_core_state_key: "core.tfstate"
        TF_VAR_environment_stage: "staging"
        TF_VAR_coaching_state_key: "coaching.tfstate"
        TF_VAR_strategy_state_key: "strategy.tfstate"

      run: |
        make core-init
        make core-deploy-auto
        echo done.
