package adaptiveCommunity
// This file has been automatically generated by `adaptive/scripts`
// The changes will be overridden by the next automatic generation.

type FieldName string
const (
	PlatformID FieldName = "platform_id"
	ID FieldName = "id"
	ChannelID FieldName = "channel"
	Active FieldName = "active"
	RequestedBy FieldName = "requested_by"
)
